# PRACTICE PROBLEMS ON FUNCTION


**<font color='red'>[MUST MAINTAIN VARIABLE NAMING CONVENTIONS FOR ALL THE TASKS]</font>**
**<font color='red'>[Solve all the tasks sequentially]</font>**


### Task 1
Write a function called **check_awesomeness** that takes a number as an argument and Checks whether the number is Awesome or not. If the number is Awesome, it returns True. Otherwise False.
 
**Awesome number:** a number where every digit is less than its immediate left digit is called an Awesome number. A single digit number cannot be a awesome number(e.g. 5421 is an Awesome number).

==========================================================

**Function Call1:**\
check_awesomeness(976321)\
**Output1:**\
True

==========================================================

**Function Call2:**\
check_awesomeness(9766321)\
**Output2:**\
False

==========================================================

**Function Call3:**\
check_awesomeness(9)\
**Output3:**\
False

==========================================================

**Function Call4:**\
check_awesomeness(78)\
**Output4:**\
False

==========================================================

**Function Call5:**\
check_awesomeness(87)\
**Output4:**\
True

In [ ]:
#todo
def check_awesomeness(number):
  str_num= str(number)
  result= True
  if len(str_num)>1:
    for i in range(1,len(str_num)):
      if (int(str_num[i])==int(str_num[i-1])) or (int(str_num[i])>int(str_num[i-1])):
        result= False
        break
  else:
    result= False
  return result
print(check_awesomeness(int(input("Enter a number: "))))

Enter a number: 87
True


### Task 2
Write a function called **check_awesome** that takes a list of numbers(integer) as an argument and Prints whether the number is Awesome or not.

**<font color='red'>Must reuse the check_awesomeness() function.</font>**

==========================================================

**Function Call1:**\
check_awesome([976321, 321, 9763221, 9742, 876, 3211])\
**Output1:**\
976321 is an awesome number.\
321 is a awesome number.\
9763221 is a not-so-awesome number.\
9742 is an awesome number.\
876 is an awesome number.\
3211 is a not-so-awesome number.

==========================================================

**Function Call2:**\
check_awesome([97821, 97210, 979210])\
**Output2:**\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.

In [ ]:
#todo
def check_awesomeness(number):
  str_num= str(number)
  result= True
  if len(str_num)>1:
    for i in range(1,len(str_num)):
      if (int(str_num[i])==int(str_num[i-1])) or (int(str_num[i])>int(str_num[i-1])):
        result= False
        break
  else:
    result= False
  return result
def check_awesomeness2(li_num):
  for num in li_num:
    result= check_awesomeness(num)
    if result== True:
      print(f"""{num} is an awesome number.""")
    else:
      print(f"""{num} is a not-so-awesome number.""")
check_awesomeness2([97821, 97210, 979210])

97821 is a not-so-awesome number.
97210 is an awesome number.
979210 is a not-so-awesome number.


### Task 3
Write a function called **find_max_min** that takes a list of numbers(integers) as a  function parameter and finds the numbers with maximum and minimum value. Then returns these two numbers as a **tuple** and prints the results using tuple unpacking in the function call accorrding to the given format. Both valid and invalid numbers should be considered for finding maximum and minimum.<font color='red'>[Must use tuple packing & unpacking] </font> 

==========================================================

**Function Call1:**\
find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output1:**\
Returned value from find_max_min() is: (9763221, 321)\
Number with maximum value is 9763221\
Number with minimum value is 321

==========================================================

**Function Call2:**\
find_max_min([97821, 1, 97210, 963, 979210, 979210])\
**Output2:**\
Returned value from find_max_min() is: (979210, 1)\
Number with maximum value is 979210\
Number with minimum value is 1

In [2]:
#todo
def find_max_min(li_num):
  max= li_num[0]
  min= li_num[0]
  for num in range(1,len(li_num)):
    if li_num[num]>max:
      max= li_num[num]
    if li_num[num]<min:
      min= li_num[num]
  return (max,min)
print( find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]))
maximum, minimum= find_max_min([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])
print(f"""Number with maximum value is {maximum}\nNumber with minimum value is {minimum}""")

(9763221, 321)
Number with maximum value is 9763221
Number with minimum value is 321


### Task 4
Write a function called **data_cleaning** that takes a string as an argument. Then gets the numbers from the given string and removes all extra spaces. Stores the clean numbers (integers) in a list and **returns** it to the function call.

==========================================================

**Function Call1:**\
data_cleaning("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]

==========================================================

**Function Call2:**\
data_cleaning("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]

==========================================================

**Function Call3:**\
data_cleaning("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]

In [ ]:
#todo
def data_cleaning(str1):
  str_li= str1.split(",")
  li_org=[]
  for num in str_li:
    i= num.strip()
    li_org.append(int(i))
  return li_org
print("Data after cleaning:",data_cleaning("976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742"))

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]


### Task 5
Write a function called **grouping_data** that takes  a list of numbers(integers) as a  function parameter and creates a dictionary where "valid", "invalid", and "duplicate" are the keys. The numbers that falls in those categories are the values.

**Valid & Invalid numbers:** A number with a minimum length of 4 and a maximum length of 6 is considered to be valid for this assignment. All the other numbers are considered to be Invalid numbers.\
**Duplicate numbers:** If a number appears more than once in the string, then that is a dupliacte number. Both valid and invalid numbers can be duplicates.

Lastly, print the dictionary **inside the function** and **return** the dictionary to the function call.

==========================================================

**Function Call1:**\
grouping_data([97821, 1, 97210, 963, 979210, 979210])\
**Output1:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]


==========================================================

**Function Call2:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211])\
**Output2:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]


==========================================================

**Function Call3:**\
grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])\
**Output3:**\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]



In [ ]:
#todo
def grouping_data(li):
  valid_li=[]
  invalid_li=[]
  dup_li=[]
  for i in li:
    if len(str(i))>=4 and len(str(i))<=6:
      if i not in valid_li:
        valid_li.append(i)
    else:
      if i not in invalid_li:
        invalid_li.append(i)
    if li.count(i)>1:
      if i not in dup_li:
        dup_li.append(i)
  dict_1={"valid":valid_li, "invalid":invalid_li, "duplicate":dup_li}
  print(f"""XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{dict_1}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX""")
  return dict_1
dict_out= grouping_data([976321, 321, 9763221, 9742, 876, 3211, 976321, 9742])
print(f"""Returned dictionary: {dict_out}\nValid number list obtained from the dictionary: {dict_out['valid']}""")

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
Valid number list obtained from the dictionary: [976321, 9742, 3211]


### Task6
Write a function called **individual_line_data** that takes a string as an argument. This function should do the following. 
* clean and prints the data.
* group the numbers in a dictionary obtained from the given string.
* check whether the **valid numbers** are awesome or not.
* find and print the maximum and minimum number among the **valid numbers** obtained from the given string.

*Hints:*\
You MUST reuse data_cleaning(), grouping_data(), check_awesome() and find_max_min() functions. 

==========================================================

**Function Call1:**\
individual_line_data("97821, 1 &nbsp;&nbsp;&nbsp;  , 97210,&nbsp;&nbsp; 963, &nbsp;&nbsp;&nbsp;979210 , 979210   ")\
**Output1:**\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210




**Function Call2:**\
individual_line_data("976321, 321&nbsp;&nbsp;,&nbsp;&nbsp;&nbsp;9763221, &nbsp;&nbsp;&nbsp;9742, 876,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3211")\
**Output2:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211



**Function Call3:**\
individual_line_data("976321, 321 ,&nbsp;&nbsp;&nbsp; 9763221, 9742, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;876, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;3211, 976321&nbsp;&nbsp;&nbsp;&nbsp;, 9742")\
**Output3:**\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211


In [ ]:
#todo
def individual_line_data(str1):
  def data_cleaning(str2):
    str_li= str2.split(",")
    li_org=[]
    for num in str_li:
      i= num.strip()
      li_org.append(int(i))
    print(f"""Data after cleaning: {li_org}""")
    return li_org
  li_org= data_cleaning(str1)
  def grouping_data(li):
    valid_li=[]
    invalid_li=[]
    dup_li=[]
    for i in li:
      if len(str(i))>=4 and len(str(i))<=6:
        if i not in valid_li:
          valid_li.append(i)
      else:
        if i not in invalid_li:
          invalid_li.append(i)
      if li.count(i)>1:
        if i not in dup_li:
          dup_li.append(i)
    dict_1={"valid":valid_li, "invalid":invalid_li, "duplicate":dup_li}
    print(f"""XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{dict_1}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX""")
    return dict_1
  number= grouping_data(li_org)
  print("Returned dictionary:",number)
  print(f"""Valid number list obtained from the dictionary: {number['valid']}""")
  print("====================================================")
  print("^^ Awesomeness checking of the Valid numbers ^^")
  def check_awesomeness(number):
    str_num= str(number)
    result= True
    if len(str_num)>1:
      for i in range(1,len(str_num)):
        if (int(str_num[i])==int(str_num[i-1])) or (int(str_num[i])>int(str_num[i-1])):
          result= False
          break
    else:
      result= False
    return result
  def check_awesomeness2(li_val):
    for num in li_val:
      result= check_awesomeness(num)
      if result== True:
        print(f"""{num} is an awesome number.""")
      else:
        print(f"""{num} is a not-so-awesome number.""")
  def find_max_min(li_num):
    max= li_num[0]
    min= li_num[0]
    for num in range(1,len(li_num)):
      if li_num[num]>max:
        max= li_num[num]
      if li_num[num]<min:
        min= li_num[num]
    return max,min
  num= check_awesomeness2(number['valid'])
  print("====================================================")
  returned_val= number['valid']
  returned_max_min= find_max_min(returned_val)
  print("Returned value from find_max_min() is:",returned_max_min)
  maximum, minimum= returned_max_min
  print(f"""Valid number with maximum value is {maximum}
Valid number with minimum value is {minimum}""")
individual_line_data("976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742")

Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}
Valid number list obtained from the dictionary: [976321, 9742, 3211]
^^ Awesomeness checking of the Valid numbers ^^
976321 is an awesome number.
9742 is an awesome number.
3211 is a not-so-awesome number.
Returned value from find_max_min() is: (976321, 3211)
Valid number with maximum value is 976321
Valid number with minimum value is 3211


### Task 7
Write a function called **number_analysis** that takes a list of strings as an argument and 
analyse those strings. \
**<font color='red'>Must reuse the individual_line_data() function.</font>**

In [ ]:
  #todo
def number_analysis(li_num):
   for string in li_num:
    str_3= string
    def individual_line_data(str1):
      def data_cleaning(str2):
        str_li= str2.split(",")
        li_org=[]
        for num in str_li:
          i= num.strip()
          li_org.append(int(i))
        print(f"""Data after cleaning: {li_org}""")
        return li_org
      li_org= data_cleaning(str1)
      def grouping_data(li):
        valid_li=[]
        invalid_li=[]
        dup_li=[]
        for i in li:
          if len(str(i))>=4 and len(str(i))<=6:
            if i not in valid_li:
              valid_li.append(i)
          else:
            if i not in invalid_li:
              invalid_li.append(i)
          if li.count(i)>1:
            if i not in dup_li:
              dup_li.append(i)
        dict_1={"valid":valid_li, "invalid":invalid_li, "duplicate":dup_li}
        print(f"""XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  Data dictionary printing inside the function:
  {dict_1}
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX""")
        return dict_1
      number= grouping_data(li_org)
      print("Returned dictionary:",number)
      print(f"""Valid number list obtained from the dictionary: {number['valid']}""")
      print("====================================================")
      print("^^ Awesomeness checking of the Valid numbers ^^")
      def check_awesomeness(number):
        str_num= str(number)
        result= True
        if len(str_num)>1:
          for i in range(1,len(str_num)):
            if (int(str_num[i])==int(str_num[i-1])) or (int(str_num[i])>int(str_num[i-1])):
              result= False
              break
        else:
          result= False
        return result
      def check_awesomeness2(li_val):
        for num in li_val:
          result= check_awesomeness(num)
          if result== True:
            print(f"""{num} is an awesome number.""")
          else:
            print(f"""{num} is a not-so-awesome number.""")
      def find_max_min(li_num):
        max= li_num[0]
        min= li_num[0]
        for num in range(1,len(li_num)):
          if li_num[num]>max:
            max= li_num[num]
          if li_num[num]<min:
            min= li_num[num]
        return max,min
      num= check_awesomeness2(number['valid'])
      print("====================================================")
      returned_val= number['valid']
      returned_max_min= find_max_min(returned_val)
      print("Returned value from find_max_min() is:",returned_max_min)
      maximum, minimum= returned_max_min
      print(f"""Valid number with maximum value is {maximum}
  Valid number with minimum value is {minimum}""")
    individual_line_data(str_3)
    print("\n\n")
number_analysis(["97821, 1     , 97210,   963,    979210 , 979210 ","976321, 321  ,   9763221,    9742, 876,        3211","976321, 321 ,    9763221, 9742,      876,       3211, 976321    , 9742"])

Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}
Valid number list obtained from the dictionary: [97821, 97210, 979210]
^^ Awesomeness checking of the Valid numbers ^^
97821 is a not-so-awesome number.
97210 is an awesome number.
979210 is a not-so-awesome number.
Returned value from find_max_min() is: (979210, 97210)
Valid number with maximum value is 979210
Valid number with minimum value is 97210



Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing ins

### Task 8
Run the following block of code for seeing the final output of this Problem.

**Output:**
######### Printing data for line no: 01 #########\
Data after cleaning: [321, 976322]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976322], 'invalid': [321], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}\
Valid number list obtained from the dictionary: [976322]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976322 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976322, 976322)\
Valid number with maximum value is 976322\
Valid number with minimum value is 976322

&emsp; 

######### Printing data for line no: 02 #########\
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [97821, 97210, 979210], 'invalid': [1, 963], 'duplicate': [979210]}\
Valid number list obtained from the dictionary: [97821, 97210, 979210]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
97821 is a not-so-awesome number.\
97210 is an awesome number.\
979210 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (979210, 97210)\
Valid number with maximum value is 979210\
Valid number with minimum value is 97210

&emsp; 

######### Printing data for line no: 03 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': []}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

&emsp;

######### Printing data for line no: 04 #########\
Data after cleaning: [976321, 321, 9763221, 9742, 876, 3211, 976321, 9742]\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Data dictionary printing inside the function:\
{'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\
Returned dictionary: {'valid': [976321, 9742, 3211], 'invalid': [321, 9763221, 876], 'duplicate': [976321, 9742]}\
Valid number list obtained from the dictionary: [976321, 9742, 3211]\
=================================================\
^_^ Awesomeness checking of the Valid numbers ^_^\
976321 is an awesome number.\
9742 is an awesome number.\
3211 is a not-so-awesome number.\
=================================================\
Returned value from find_max_min() is: (976321, 3211)\
Valid number with maximum value is 976321\
Valid number with minimum value is 3211

In [ ]:
lines_of_data = [
    "321 ,   976322",
    "97821, 1 , 97210, 963, 979210 , 979210",
    "976321, 321 ,   9763221, 9742, 876, 3211",
    "976321, 321 ,   9763221, 9742, 876, 3211, 976321, 9742"
]
def number_analysis(li_num):
   count=1
   for string in li_num:
    print(f"""######### Printing data for line no: 0{count} #########""")
    str_3= string
    def individual_line_data(str1):
      def data_cleaning(str2):
        str_li= str2.split(",")
        li_org=[]
        for num in str_li:
          i= num.strip()
          li_org.append(int(i))
        print(f"""Data after cleaning: {li_org}""")
        return li_org
      li_org= data_cleaning(str1)
      def grouping_data(li):
        valid_li=[]
        invalid_li=[]
        dup_li=[]
        for i in li:
          if len(str(i))>=4 and len(str(i))<=6:
            if i not in valid_li:
              valid_li.append(i)
          else:
            if i not in invalid_li:
              invalid_li.append(i)
          if li.count(i)>1:
            if i not in dup_li:
              dup_li.append(i)
        dict_1={"valid":valid_li, "invalid":invalid_li, "duplicate":dup_li}
        print(f"""XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{dict_1}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX""")
        return dict_1
      number= grouping_data(li_org)
      print("Returned dictionary:",number)
      print(f"""Valid number list obtained from the dictionary: {number['valid']}""")
      print("====================================================")
      print("^^ Awesomeness checking of the Valid numbers ^^")
      def check_awesomeness(number):
        str_num= str(number)
        result= True
        if len(str_num)>1:
          for i in range(1,len(str_num)):
            if (int(str_num[i])==int(str_num[i-1])) or (int(str_num[i])>int(str_num[i-1])):
              result= False
              break
        else:
          result= False
        return result
      def check_awesomeness2(li_val):
        for num in li_val:
          result= check_awesomeness(num)
          if result== True:
            print(f"""{num} is an awesome number.""")
          else:
            print(f"""{num} is a not-so-awesome number.""")
      def find_max_min(li_num):
        max= li_num[0]
        min= li_num[0]
        for num in range(1,len(li_num)):
          if li_num[num]>max:
            max= li_num[num]
          if li_num[num]<min:
            min= li_num[num]
        return max,min
      num= check_awesomeness2(number['valid'])
      print("====================================================")
      returned_val= number['valid']
      returned_max_min= find_max_min(returned_val)
      print("Returned value from find_max_min() is:",returned_max_min)
      maximum, minimum= returned_max_min
      print(f"""Valid number with maximum value is {maximum}
Valid number with minimum value is {minimum}""")
    individual_line_data(str_3)
    print("\n\n")
    count+=1
number_analysis(lines_of_data)

######### Printing data for line no: 01 #########
Data after cleaning: [321, 976322]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [976322], 'invalid': [321], 'duplicate': []}
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Returned dictionary: {'valid': [976322], 'invalid': [321], 'duplicate': []}
Valid number list obtained from the dictionary: [976322]
^^ Awesomeness checking of the Valid numbers ^^
976322 is a not-so-awesome number.
Returned value from find_max_min() is: (976322, 976322)
Valid number with maximum value is 976322
Valid number with minimum value is 976322



######### Printing data for line no: 02 #########
Data after cleaning: [97821, 1, 97210, 963, 979210, 979210]
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Data dictionary printing inside the function:
{'valid': [97821, 97210, 979